from selenium.webdriver.common.by import By
class HomePageLocators():
    SIGN_IN_LINK = (By.CSS_SELECTOR, ".authorization-link")
    CREATE_ACCOUNT_LINK = (By.XPATH, "//a[text()='Create an Account']")
    WOMEN_LINK = (By.CSS_SELECTOR,".ui-menu-icon")
    WOMEN_TOPS_LINK = (By.CSS_SELECTOR,"a#ui-id-9>span:nth-child(2)")
    WOMEN_TOPS_JACKETS_LINK = (By.CSS_SELECTOR,"a#ui-id-11>span")
    WHATS_NEW = (By.CSS_SELECTOR,"#ui-id-3")
    WOMEN = (By.CSS_SELECTOR,"#ui-id-4")
    MEN = (By.CSS_SELECTOR,"#ui-id-5")
    GEAR = (By.CSS_SELECTOR,"#ui-id-6")
    TRAINING = (By.CSS_SELECTOR,"#ui-id-7")
    SALE = (By.CSS_SELECTOR,"#ui-id-8")
    SHOP_NEW_YOGA = (By.CSS_SELECTOR,".action.more.button")
    SHOP_PANTS = (By.CSS_SELECTOR,".action.more.icon")
    SHOP_ERIN_RECOMMENDS = (By.CSS_SELECTOR,".home-erin>.content>.action.more.icon")
    SHOP_TEES = (By.CSS_SELECTOR,".home-t-shirts>.content>.action.more.icon")
    SHOP_PERFORMANCE = (By.CSS_SELECTOR,".home-performance>.content>.action.more.icon")
    SHOP_ECO_FRIENDLY = (By.CSS_SELECTOR,".home-eco>.content>.action.more.icon")
class CreateAccountLocators():
    FIRST_NAME = (By.CSS_SELECTOR,"input#firstname")
    LAST_NAME = (By.CSS_SELECTOR, "input#lastname")
    EMAIL = (By.CSS_SELECTOR,"input#email_address")
    PASSWORD = (By.CSS_SELECTOR, "input#password")
    PASSWORD_CONFIRMATION = (By.CSS_SELECTOR, "input#password-confirmation")
    BUTTON_CREATE_ACCOUNT = (By.CSS_SELECTOR,"button.primary>span")
class LoginPageLocators():
    INPUT_EMAIL = (By.CSS_SELECTOR, "input#email")
    INPUT_PASS = (By.CSS_SELECTOR, "input#pass")
    SIGN_IN = (By.CSS_SELECTOR,"#send2>span")
class JacketsWomenLocators():
    SHOW_CART_WINDOW = (By.CSS_SELECTOR, ".showcart")
    VIEW_CART_PAGE = (By.CSS_SELECTOR, ".viewcart>span")

    OLIVIA_NAME = (By.CSS_SELECTOR,"a.product-item-link")
    OLIVIA_SIZE = (By.CSS_SELECTOR,"#option-label-size-143-item-168")
    OLIVIA_COLOR = (By.CSS_SELECTOR,"#option-label-color-93-item-57")
    BUTTON_ADD_OLIVIA_TO_CART = (By.CSS_SELECTOR,"button.tocart>span")

    JUNO_NAME = (By.CSS_SELECTOR,"li:nth-child(2)  a.product-item-link")
    JUNO_SIZE = (By.CSS_SELECTOR,"li:nth-child(2) #option-label-size-143-item-167")
    JUNO_COLOR = (By.CSS_SELECTOR,"li:nth-child(2) #option-label-color-93-item-53")
    BUTTON_ADD_JUNO_TO_CART = (By.CSS_SELECTOR, "li:nth-child(2) .tocart>span")

    NEVE_NAME = (By.CSS_SELECTOR, "li:nth-child(3)  a.product-item-link")
    NEVE_SIZE_XS = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-166")
    NEVE_SIZE_S = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-167")
    NEVE_SIZE_M = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-168")
    NEVE_SIZE_L = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-169")
    NEVE_SIZE_XL = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-170")
    NEVE_COLOR_BLACK = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-49")
    NEVE_COLOR_BLUE = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-50")
    NEVE_COLOR_ORANGE = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-56")
    BUTTON_ADD_NEVE_TO_CART = (By.CSS_SELECTOR, "li:nth-child(3) .tocart>span")

    NADIA_NAME = (By.CSS_SELECTOR, "li:nth-child(4)  a.product-item-link")
    NADIA_SIZE_XS = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-166")
    NADIA_SIZE_S = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-167")
    NADIA_SIZE_M = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-168")
    NADIA_SIZE_L = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-169")
    NADIA_SIZE_XL = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-size-143-item-170")
    NADIA_COLOR_BLACK = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-49")
    NADIA_COLOR_ORANGE = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-56")
    NADIA_COLOR_YELLOW = (By.CSS_SELECTOR, "li:nth-child(3) #option-label-color-93-item-60")
    BUTTON_ADD_NADIA_TO_CART = (By.CSS_SELECTOR, "li:nth-child(4) .tocart>span")

class CartWindowLocators():
    NAME = (By.CSS_SELECTOR,".product-item-name>a")
    Quantity = (By.CSS_SELECTOR,"span.count")
    SEE_DETAILS = (By.CSS_SELECTOR, (".toggle>span"))
    SIZE = (By.CSS_SELECTOR,"dd.values:nth-child(2)")
    COLOR = (By.CSS_SELECTOR,"dd.values:nth-child(4)")
class SuccessfulMessageLOCATORS():
    SUCCESS_MESSAGE = (By.CSS_SELECTOR,".messages>.message-success>div")
    LINK_TO_CART_FROM_SUCCESS_MESSAGE = (By.CSS_SELECTOR,".messages>.message-success>div>a")
class MenPageLocators():
    MEN_TOPS_LINK = (By.CSS_SELECTOR,"ol>li>a")
    MEN_BOTTOMS_LINK =(By.CSS_SELECTOR,"ol>li:nth-child(2)>a")
    MEN_HOODIES_LINK = (By.CSS_SELECTOR,".categories-menu>ul>li>a")
    MEN_JACKET_LINK = (By.CSS_SELECTOR,".categories-menu>ul>li:nth-child(2)>a")
    MEN_TEES_LINK = (By.CSS_SELECTOR,".categories-menu>ul>li:nth-child(3)>a")
    MEN_TANKS_LINK = (By.CSS_SELECTOR,".categories-menu>ul>li:nth-child(4)>a")
    MEN_PANTS_LINK = (By.CSS_SELECTOR,".categories-menu>ul:nth-child(4)>li>a")
    MEN_SHORTS_LINK = (By.CSS_SELECTOR,".categories-menu>ul:nth-child(4)>li:nth-child(2)>a")
class WomenPageLocators():
    WOMEN_TOPS_LINK = (By.CSS_SELECTOR, "ol>li>a")
    WOMEN_BOTTOMS_LINK = (By.CSS_SELECTOR, "ol>li:nth-child(2)>a")
    WOMEN_HOODIES_LINK = (By.CSS_SELECTOR, ".categories-menu>ul>li>a")
    WOMEN_JACKETS_LINK = (By.CSS_SELECTOR, ".categories-menu>ul>li:nth-child(2)>a")
    WOMEN_TEES_LINK = (By.CSS_SELECTOR, ".categories-menu>ul>li:nth-child(3)>a")
    WOMEN_BRASS_LINK = (By.CSS_SELECTOR, ".categories-menu>ul>li:nth-child(4)>a")
    WOMEN_PANTS_LINK = (By.CSS_SELECTOR, ".categories-menu>ul:nth-child(4)>li>a")
    WOMEN_SHORTS_LINK = (By.CSS_SELECTOR, ".categories-menu>ul:nth-child(4)>li:nth-child(2)>a")